# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='service',
            field=models.ForeignKey(db_column='service_no', on_delete=django.db.models.deletion.CASCADE, to='customers.Service'),
        ),
    ]
