# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_Loyalty',
            field=models.IntegerField(help_text='years'),
        ),
    ]
