# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20170414_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Salary',
            field=models.ForeignKey(help_text='&#36;', on_delete=django.db.models.deletion.CASCADE, related_name='salary_customer', to='customers.Salary'),
        ),
    ]
