# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20170415_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Account_Type',
            field=models.IntegerField(choices=[(0, 'Current Account'), (1, 'Savings Account')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Employer_Stability',
            field=models.IntegerField(choices=[(0, 'Unstable'), (1, 'Stable')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Employment',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Contract'), (2, 'Permanent')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Residential_Status',
            field=models.IntegerField(choices=[(0, 'Rented'), (1, 'Owned')]),
        ),
    ]
