# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20170415_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Account_Type',
            field=models.CharField(choices=[('Current Account', 'Current Account'), ('Savings Account', 'Savings Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.CharField(choices=[('60 +', '60 +'), ('36 - 59', '36 - 59'), ('18 - 35', '18 - 35')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Education',
            field=models.CharField(choices=[('Highschool and below', 'Highschool and below'), ('Tertiary and above', 'Tertiary and above')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Employer_Stability',
            field=models.CharField(choices=[('Unstable', 'Unstable'), ('Stable', 'Stable')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Employment',
            field=models.CharField(choices=[('Student', 'Student'), ('Contract', 'Contract'), ('Permament', 'Permanent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Residential_Status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Owned', 'Owned')], max_length=10),
        ),
    ]
