# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20170415_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemanager',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicemanager',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceManager',
        ),
    ]
