# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20170415_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
