# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='service',
            new_name='Service_Level',
        ),
    ]
