# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20170417_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
