# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20170417_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
    ]
