# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_auto_20170417_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Service_Level',
            field=models.ForeignKey(blank=True, db_column='service_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Service'),
        ),
    ]
