# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20170417_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_no',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Service_Level',
            field=models.ForeignKey(blank=True, db_column='service_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
