# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20170417_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('customer', models.ForeignKey(db_column='Customer_ID', on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('service', models.ForeignKey(db_column='service_no', on_delete=django.db.models.deletion.CASCADE, to='customers.Service')),
            ],
            options={
                'ordering': ['-from_date'],
                'db_table': 'service_manager',
            },
        ),
        migrations.RemoveField(
            model_name='salary',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
