# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_loyalty', models.IntegerField(choices=[(0, '0 - 2 years'), (1, '3 - 10 years')])),
            ],
            options={
                'ordering': ['customer_loyalty'],
            },
        ),
    ]
