# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True,  serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField(default=True, primary_key=True,)),
                ('Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=30)),
                ('Account_Type', models.CharField(max_length=10)),
                ('Age', models.IntegerField(default=True)),
                ('Education', models.IntegerField(blank=True, default=0)),
                ('Employment', models.IntegerField(blank=True, default=0)),
                ('Salary', models.IntegerField(default=True)),
                ('Employer_Stability', models.IntegerField(blank=True, default=0)),
                ('Customer_Loyalty', models.IntegerField(blank=True, default=0)),
                ('Balance', models.IntegerField(blank=True, default=0)),
                ('Residential_Status', models.IntegerField(blank=True, default=0)),
                ('Service_Level', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
