# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Customer_ID',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
