# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170313_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Customer_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='services',
            table='services_services',
        ),
    ]
