# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170313_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Education',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='Employer_Stability',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='Employment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='Residential_Status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='Service_Level',
            field=models.CharField(max_length=30),
        ),
    ]
