# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170326_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_rating', models.IntegerField(choices=[(0, 'Silver'), (1, 'Gold'), (2, 'Platinum')])),
                ('comment', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='Service_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Levels'),
        ),
    ]
