# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170326_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Level',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
